FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
COPY frontend/package.json ./frontend/

RUN yarn install --frozen-lockfile

# Copy frontend source
COPY frontend ./frontend

WORKDIR /app/frontend

EXPOSE 80

CMD ["yarn", "dev"]
